apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name}}
  namespace: {{ .Values.deployment.namespace}}
  labels:
    project: {{ .Values.deployment.project}}
    component: {{ .Values.deployment.component}}
    tier: {{ .Values.deployment.tier}}
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"