apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name}}
  namespace: {{ .Values.deployment.namespace}}
  labels:
    project: {{ .Values.deployment.project}}
    component: {{ .Values.deployment.component}}
    tier: {{ .Values.deployment.tier}}
data:
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_URL: "redis://redis:6379"
  MONGO: "true"