apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
  namespace: {{ .Values.service.namespace}}
  labels:
    project: {{ .Values.service.project}}
    component: {{ .Values.service.component}}
    tier: {{ .Values.service.tier}}
spec:
  selector:
    project: {{ .Values.service.project}}
    component: {{ .Values.service.component}}
    tier: {{ .Values.service.tier}}
  
  ports:
  - protocol: TCP
    port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.targetPort}}