deployment:
  imageURL: teja142/rabbitmq
  imageVersion: optv1
  name: rabbitmq
  namespace: roboshop
  tier: app
  project: roboshop
  component: rabbitmq

service: 
  name: rabbitmq
  namespace: roboshop
  tier: app
  project: roboshop
  component: rabbitmq
  port: 5672
  targetPort: 5672

secret:
  name: rabbitmq
  namespace: roboshop
  tier: app
  project: roboshop
  component: rabbitmq
