apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name}}
  namespace: {{ .Values.deployment.namespace}}
  labels:
    project: {{ .Values.deployment.project}}
    component: {{ .Values.deployment.component}}
    tier: {{ .Values.deployment.tier}}
spec:
  selector:
    project: {{ .Values.deployment.project}}
    component: {{ .Values.deployment.component}}
    tier: {{ .Values.deployment.tier}}
  
  ports:
  - protocol: TCP
    port: {{ .Values.deployment.port}}
    targetPort: {{ .Values.deployment.targetPort}}