deployment:
  imageURL: teja142/redis
  imageVersion: optv1
  name: redis
  namespace: roboshop
  tier: app
  project: roboshop
  component: redis

service: 
  name: redis
  namespace: roboshop
  tier: app
  project: roboshop
  component: redis
  port: 6379
  targetPort: 6379

secret:
  name: redis
  namespace: roboshop
  tier: app
  project: roboshop
  component: redis
